### ISSUE TITLE
Data not aggregated in prefork mode

### ISSUE THREAD

**Issue by marghidanu** [tyldum/mojolicious-plugin-prometheus#13]
When running under **hypnotoad** the data does dot get aggregated for the application instance, instead each worker is responding with a different value for the **http_requests_total** value. This is a problem since the whole point for this is to aggregate data at the application level.

**Comment by tyldum** [comment]
In order to resolve this we would need to introduce a storage backend for it, as there is nothing shared between the hypnotoad workers. My current use-case is without hypnotoad.

Looking into possible solutions, suggestions/PRs welcome.

**Comment by marghidanu** [comment]
Actually the problem lies in the declaration of the Net::Prometheus object, I'll send you a PR in a few minutes. :)

**Comment by tyldum** [comment]
Discussing solutions with some of the core Mojo devs, there is no quick fix since hypnotoad is just a thin layer without any state. Not sure what solution you had in mind?
Shared memory might be an option, or add zmq or redis into the mix. But that doesn't feel right either.
In our dockerized environment we just scale out standalone processes instead of using hypnotoad.

**Comment by marghidanu** [comment]
Sorry for the late response I thought I could fix it by sharing memory but the problem is with the prefork model, basically copy-on-write is screwing us. 

**Mojolicious::Plugin::ServerStatus** this plugin seems to do it via Parallel::Scoreboard and its very nice. I will explore this option.

**Comment by lammel** [comment]
Just ran into the issue when validating the data in Grafana/Prometheus.

I would suggest to simple add a tag {worker="$pid"} to each metric returned. This will ensure automatic aggregation in prometheus and also allow to detect further issues with a specific worker.

I guess that would solve the issue at the right place.

**Comment by lammel** [comment]
With the changes in PR #14 the workers will now report their worker process id as label. Hence over time different workers will answer the metrics request and metrics are correct over time (using a rate of e.g. 5m should be fine, when querying in 15s interval).

To correct the remaining issue with the Net::Prometheus::ProcessCollector a patch would be required there to allow to dynamically add the process id on add the sample, instead of upfront during initialization. But that is not possible currently without overriding the class.

**Comment by tyldum** [comment]
With #14 merged there is at least a label to indicate which worker is the source. Thanks @lammel.
Global aggregated metrics is still a goal, but I feel the current solutions for that cause too much overhead for a simple monitoring solution.

**Comment by tyldum** [comment]
Did a small proof of concept here: https://gist.github.com/tyldum/7989ce167e181c306cd4c97b69c5e779
Comments welcome (using CHI might be unnecessary, but provides an easy interface).

**Comment by tyldum** [comment]
https://github.com/tyldum/Mojolicious-Plugin-Prometheus-Shared-FastMmap should solve this.
Adds a mmapped cache to which each worker will dump stats after each request served.
No idea how sane it is, and I have not tested the performance impact.
